//===============================================================================//
//            PLEASE DO NOT modify basic I/O name or top module name!            //
//===============================================================================//
// median_v2 — same function as median.v / tb_median:
//   Five 6-bit one-hot inputs encode values 0..5; out is the one-hot value of the
//   median (3rd order statistic). Tie/duplicate handling matches the testbench.
//
// Improvements over median.v:
//   * Prefix sums reuse shared partial sums (s01, s23) → shallower adder tree.
//   * Median index via explicit priority chain (comparator + mux view), then a
//     6-bit one-hot decoder (out = 1 << idx) instead of six separate out[i] gates.
//   * Combinational only.
//===============================================================================//

module median (a0, a1, a2, a3, a4, out);

  input [5:0] a0, a1, a2, a3, a4;

  output [5:0] out;

  // Histogram: s[k] = how many inputs have value k (column sums).
  wire [2:0] s0, s1, s2, s3, s4, s5;

  assign s0 = a0[0] + a1[0] + a2[0] + a3[0] + a4[0];
  assign s1 = a0[1] + a1[1] + a2[1] + a3[1] + a4[1];
  assign s2 = a0[2] + a1[2] + a2[2] + a3[2] + a4[2];
  assign s3 = a0[3] + a1[3] + a2[3] + a3[3] + a4[3];
  assign s4 = a0[4] + a1[4] + a2[4] + a3[4] + a4[4];
  assign s5 = a0[5] + a1[5] + a2[5] + a3[5] + a4[5];

  // Prefix counts: c[k] = #{ inputs with value <= k } (shared adder subtrees).
  wire [2:0] s01  = s0 + s1;
  wire [2:0] s23  = s2 + s3;
  wire [2:0] c0   = s0;
  wire [2:0] c1   = s01;
  wire [2:0] c2   = s01 + s2;
  wire [2:0] c3   = s01 + s23;
  wire [2:0] c4   = s01 + s23 + s4;
  wire [2:0] c5   = s01 + s23 + s4 + s5;

  // Smallest k with c[k] >= 3 is the median value (matches tb_median).
  wire [2:0] med_idx =
      (c0 >= 3'd3) ? 3'd0 :
      (c1 >= 3'd3) ? 3'd1 :
      (c2 >= 3'd3) ? 3'd2 :
      (c3 >= 3'd3) ? 3'd3 :
      (c4 >= 3'd3) ? 3'd4 : 3'd5;

  assign out = 6'd1 << med_idx;

endmodule


//Generated by Cursor