//===============================================================================//
//            PLEASE DO NOT modify basic I/O name or top module name!            //
//===============================================================================//
// voting_v2.v — same I/O and tie rule as voting.v, different datapath (faster-style
// encoder + compare tree vs bit-column adders + priority if/else in voting.v):
//
//   * One-hot → 3-bit index via parallel weighted sum per input (homework one-hot).
//   * Tallies: five parallel 3-bit equality compares per bucket, then small adds.
//   * Winner: 4-deep max2_pick tournament; ties → larger candidate index wins.
//
// Combinational only; no registers.
//===============================================================================//

module voting (a0, a1, a2, a3, a4, out, count);

  input [4:0] a0, a1, a2, a3, a4;

  output reg [4:0] out;
  output reg [2:0] count;

  // Parallel one-hot → index (valid for homework one-hot inputs only).
  wire [2:0] i0 = a0[4] * 3'd4 + a0[3] * 3'd3 + a0[2] * 3'd2 + a0[1] * 3'd1;
  wire [2:0] i1 = a1[4] * 3'd4 + a1[3] * 3'd3 + a1[2] * 3'd2 + a1[1] * 3'd1;
  wire [2:0] i2 = a2[4] * 3'd4 + a2[3] * 3'd3 + a2[2] * 3'd2 + a2[1] * 3'd1;
  wire [2:0] i3 = a3[4] * 3'd4 + a3[3] * 3'd3 + a3[2] * 3'd2 + a3[1] * 3'd1;
  wire [2:0] i4 = a4[4] * 3'd4 + a4[3] * 3'd3 + a4[2] * 3'd2 + a4[1] * 3'd1;

  wire [2:0] c0, c1, c2, c3, c4;

  assign c0 = (i0 == 3'd0) + (i1 == 3'd0) + (i2 == 3'd0) + (i3 == 3'd0) + (i4 == 3'd0);
  assign c1 = (i0 == 3'd1) + (i1 == 3'd1) + (i2 == 3'd1) + (i3 == 3'd1) + (i4 == 3'd1);
  assign c2 = (i0 == 3'd2) + (i1 == 3'd2) + (i2 == 3'd2) + (i3 == 3'd2) + (i4 == 3'd2);
  assign c3 = (i0 == 3'd3) + (i1 == 3'd3) + (i2 == 3'd3) + (i3 == 3'd3) + (i4 == 3'd3);
  assign c4 = (i0 == 3'd4) + (i1 == 3'd4) + (i2 == 3'd4) + (i3 == 3'd4) + (i4 == 3'd4);

  wire [2:0] w43_c, w43_i, w21_c, w21_i, w321_c, w321_i, wfinal_c, wfinal_i;

  max2_pick U43 (
      .ca(c4),
      .ia(3'd4),
      .cb(c3),
      .ib(3'd3),
      .oc(w43_c),
      .oi(w43_i)
  );
  max2_pick U21 (
      .ca(c2),
      .ia(3'd2),
      .cb(c1),
      .ib(3'd1),
      .oc(w21_c),
      .oi(w21_i)
  );
  max2_pick U321 (
      .ca(w43_c),
      .ia(w43_i),
      .cb(w21_c),
      .ib(w21_i),
      .oc(w321_c),
      .oi(w321_i)
  );
  max2_pick Ufinal (
      .ca(w321_c),
      .ia(w321_i),
      .cb(c0),
      .ib(3'd0),
      .oc(wfinal_c),
      .oi(wfinal_i)
  );

  always @(*) begin
    out   = 5'd1 << wfinal_i;
    count = wfinal_c;
  end

endmodule

module max2_pick (
    input  [2:0] ca,
    input  [2:0] ia,
    input  [2:0] cb,
    input  [2:0] ib,
    output reg [2:0] oc,
    output reg [2:0] oi
);
  always @(*) begin
    if (ca > cb) begin
      oc = ca;
      oi = ia;
    end else if (cb > ca) begin
      oc = cb;
      oi = ib;
    end else begin
      oc = ca;
      oi = (ia > ib) ? ia : ib;
    end
  end
endmodule


// Generated by Cursor